package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController // This means this class is a REST Controller that returns JSON
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @PostMapping(path = "/add") // Map ONLY POST Requests
  public String addNewUser(@RequestParam String name, @RequestParam String email) {
    // @RequestParam means it is a parameter from the GET or POST request

    User n = new User();
    n.setName(name);
    n.setEmail(email);
    userRepository.save(n);
    return "Saved";
  }

  @GetMapping(path = "/all")
  public Iterable<User> getAllUsers() {
    // This returns a JSON with all users
    return userRepository.findAll();
  }

  @GetMapping(path = "/{id}")
  public User getUserById(@PathVariable Integer id) {
    // Get a user by ID and return it as JSON
    return userRepository.findById(id).orElse(null);
  }
}