package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController // This means this class is a REST Controller that returns JSON
@RequestMapping(path = "/") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @PostMapping(path = "/add")
  public String addNewUser(@RequestParam String name, @RequestParam String email) {

    User n = new User();
    n.setName(name);
    n.setEmail(email);
    userRepository.save(n);
    return "Saved";
  }

  @GetMapping(path = "/all")
  public Iterable<User> getAllUsers() {
    return userRepository.findAll();
  }

  @GetMapping(path = "/get/{id}")
  public User getUserById(@PathVariable Integer id) {
    return userRepository.findById(id).orElse(null);
  }

  @PutMapping(path = "/update/{id}")
  public User updateUser(@PathVariable Integer id, @RequestBody User userDetails) {
    return userRepository.findById(id)
        .map(user -> {
          user.setUsername(userDetails.getUsername());
          user.setPassword(userDetails.getPassword());
          user.setRole(userDetails.getRole());
          user.setEmail(userDetails.getEmail());
          user.setName(userDetails.getName());
          return userRepository.save(user);
        })
        .orElse(null);
  }
}